version: 2.1

# Tested these commands locally with Docker Desktop. To test locally, run this command:
# docker run -it -v [location of The-Feed code on your pc]:/home/circleci/project mechlizard/the-feed-web:latest
# Project will be mounted to /home/circleci/project

# Notes:
# cd /home/circleci/project
# Install mongodb
# curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
#   sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
#   --dearmor
# echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
# sudo apt-get update
# sudo apt-get install -y mongodb-org
# Then had to do this to fix mongodb compass install: apt --fix-broken install
#
# Install mongoDB compass:
# wget https://downloads.mongodb.com/compass/mongodb-compass_1.28.1_amd64.deb
# sudo dpkg -i mongodb-compass_1.28.4_amd64.deb
# node MERN/backend_server/server.js
# npm install
# npm install express mongoose bcryptjs jsonwebtoken body-parser cors
# npm install n stable

# Define an executor
executors:
  docker_executor:
    docker:
      - image: mechlizard/the-feed-web

jobs:
  build:
    executor: docker_executor
    steps:
      - checkout
      # If latest node is required
      #- run:
      #    name: Installing Node
      #    command: |
      #      curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
      #      sudo -E bash nodesource_setup.sh
      #      sudo apt-get install -y nodejs
      - run:
          name: Compile Code
          # Compile just the regular program and the program with Catch2
          command: |
            cd /home/circleci/project
      # Allows "build" environment to persist into the "test" phase
      #- persist_to_workspace:
      #    root: /home/circleci/project
      #    paths:
      #      - the_feed_test.exe
  #test:
  #  executor: docker_executor
  #  steps:
  #    - attach_workspace:
  #        at: /home/circleci/project/
  #    - run:
  #        name: Run Code
  #        command: '/home/circleci/project/the_feed_test.exe'


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build