version: 2.1

# Define an executor
executors:
  docker_executor:
    docker:
      - image: mechlizard/the-feed-web
      #- image: circleci/node:latest

jobs:
  build:
    executor: docker_executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install docker-compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose --version
      - attach_workspace:
          at: /home/circleci/project/
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.yaml exec web npm test


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build